language: go
script:
  - go test
  - wget https://gist.githubusercontent.com/030/da7c28869ae69fc4c02634e253ab615b/raw/6c4dd1b8243c4a5085902f34165d7e28a4a3e470/go-releases.sh
  - chmod +x ./go-releases.sh
  - ./go-releases.sh
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - go-yq-darwin
    - go-yq-darwin.sha512.txt
    - go-yq-linux
    - go-yq-linux.sha512.txt
    - go-yq-windows.exe
    - go-yq-windows.exe.sha512.txt
  skip_cleanup: true
  on:
    tags: true