language: go
script:
  - go test
  - ./releases.sh
deploy:
  provider: releases
  api_key: hK6rvARvN077f8bN4hLTw4ALvg9dNt4iwGEHd9tki6/XLKS5J05dHMXMJKvSaQqYX9wWc4fZBM1VGGhZ9y9ltqgjlBm6EBsX+1iDtXHqKdNt3TsIDVrPD5K9B4f3QMLnT2fTpeA46VBGWaNInzi3GSGt6pWdVoi4HoT0c6rdrRxqnW5XsTj9doVbwntVa4N/UbWWTbIG1aoYN1oAvnabZvxvMSnOfF1iS2pv5Te4Vokzc5koVL4/DETffxtYY2/AUimXxPlfjutrC3Sk1oIDhxYEceeraQY4ILt/6IgiYsWBhvJihDgISF9us8HE2OvOkhy20/DVHOs/pODDscVMfdDaGvF17dTLo82MieUdrcsuvlkInluyP+fXUoGKc7ZgHNeOH9am1LX4MMJEPG5cOo9ynjn2whPrAXFFi3DFerGYn8cRnWvwdACXOu7RYQLwcPHFzmauTup893V7+Xoe5LVkzmfQsl5y6pnv8n7wopx42fhoQFoqncBXk8i/IkRt7g6KdrFDli6nfwLCQGHVaar/ezKNgomjoyt+1VYaKUZlcmu/Pi9krF/ZFapE8lxtVpaA1E+AOo5yIpjHyCvP5G2JWCLFI2ffsA6ziJBOEtbK9/9bAozdZUzdqxUZLkgXy9p0kPLOv7+orVInMwq+sQUQn2n+HcIraS/94P2KVBg=
  file:
    - go-yq-darwin
    - go-yq-darwin.sha512.txt
    - go-yq-linux
    - go-yq-linux.sha512.txt
    - go-yq-windows.exe
    - go-yq-windows.exe.sha512.txt
  skip_cleanup: true
  on:
    tags: true